name: Build Package
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: windows-latest
            cmd: npm run buildWindows
            artifact: windows-package
            path: |
              dist/app/*.zip
              dist/app/*.exe
    env:
      SDKROOT: ${{ matrix.env.SDKROOT }}
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 20
    - run: npm install --omit=optional
    - name: build package
      run: ${{ matrix.cmd }}
    - name: upload package
      uses: actions/upload-artifact@v4
      with:
        name: ${{ matrix.artifact }}
        path: ${{ matrix.path }}
